export const QUARTER_INFO = [
  '3F OIL PALM AGROTECH',
  'A BROWN ENERGY AND RESOURCES DEVELOPMENT, INC. (ABERDI)',
  'ABAGO S.A.S.',
  'ABDI BUDI MULIA',
  'ABEDON OIL MILL SDN. BHD.',
  'ACE OIL MILL SDN BHD',
  'ACEITAGRO S.A.',
  'ACEITE CHIAPANECA LA PALMA S. DE P.R. DE R.L. DE C.V.',
  'ACEITES DE PALMA',
  'ACEITES LAS COLOMBIANAS (ALASCOL) S.A.S.',
  'ACEITES MANUELITA'
]

export const PRODUCTS = [
  '3F OIL PALM AGROTECH',
  'A BROWN ENERGY AND RESOURCES DEVELOPMENT, INC. (ABERDI)',
  'ABAGO S.A.S.',
  'ABDI BUDI MULIA',
  'ABEDON OIL MILL SDN. BHD.',
  'ACE OIL MILL SDN BHD',
  'ACEITAGRO S.A.',
  'ACEITE CHIAPANECA LA PALMA S. DE P.R. DE R.L. DE C.V.',
  'ACEITES DE PALMA',
  'ACEITES LAS COLOMBIANAS (ALASCOL) S.A.S.',
  'ACEITES MANUELITA'
]

export const PARENT_BUSINESS = [
  '3F OIL PALM AGROTECH',
  'A BROWN ENERGY AND RESOURCES DEVELOPMENT, INC. (ABERDI)',
  'ABAGO S.A.S.',
  'ABDI BUDI MULIA',
  'ABEDON OIL MILL SDN. BHD.',
  'ACE OIL MILL SDN BHD',
  'ACEITAGRO S.A.',
  'ACEITE CHIAPANECA LA PALMA S. DE P.R. DE R.L. DE C.V.',
  'ACEITES DE PALMA',
  'ACEITES LAS COLOMBIANAS (ALASCOL) S.A.S.',
  'ACEITES MANUELITA'
]

export const CROP = ['CROP 1', 'CROP_2', 'CROP_3']
